# 此配置文件用于存放项目数据库连接信息
[mysql] # mysql 数据库默认
host = "192.168.9.118"
user = "root"
port = 3306
password = "Passw0rd@ylzl"
database = "xgate"
charset = "utf8mb4"
pool_mincached = 1
pool_maxcached = 4
pool_maxconnections = 10
pool_blocking = true


[redis] # redis 数据库默认
host = "192.168.9.118"
port = 6379
password = "Passw0rd@ylzl"
db = "0"
max_connections = 4
